from pattern_count import PatternCount
print "importing"

# pattern = "la"

# print PatternCount(text, pattern)

def FrequentWords(text, k):
    print "start"
    frequentPatterns = {}
    for i in range(0, len(text) - k+1):
        # print text[i: i + k]
        pattern = text[i: i + k]
        count = PatternCount(text, pattern)
        frequentPatterns[pattern] = count
        print pattern, count
    #     count = PatternCount(text, pattern)

    print frequentPatterns
    print max(frequentPatterns, key=frequentPatterns.get)
    maxvalue = max(frequentPatterns.viewvalues())

    maxpatterns = []
    for key, value in frequentPatterns.iteritems():
        print value
        if value == maxvalue:
            maxpatterns.append(key)
    print " ".join(maxpatterns)



text = "GGACTCGGTCAGACTTAAAGATTATAAATAATTATAAATATGCAGATTCGGACTCGGTCTGCAGATTCATTATAAATATGCAGATTCATTATAAATAAGACTTAAAGATTATAAATAGGACTCGGTCAGACTTAAAGAGACTTAAAGAGACTTAAAGCGAGTAAGTGCAGATTCCGAGTAAGATTATAAATACGAGTAAGATTATAAATATGCAGATTCGGACTCGGTCCGAGTAAGTGCAGATTCAGACTTAAAGCGAGTAAGGGACTCGGTCGGACTCGGTCGGACTCGGTCAGACTTAAAGTGCAGATTCAGACTTAAAGTGCAGATTCTGCAGATTCAGACTTAAAGGGACTCGGTCCGAGTAAGGGACTCGGTCTGCAGATTCCGAGTAAGGGACTCGGTCGGACTCGGTCATTATAAATAATTATAAATAAGACTTAAAGAGACTTAAAGAGACTTAAAGTGCAGATTCAGACTTAAAGTGCAGATTCCGAGTAAGCGAGTAAGAGACTTAAAGTGCAGATTCAGACTTAAAGAGACTTAAAGTGCAGATTCTGCAGATTCCGAGTAAGATTATAAATACGAGTAAGAGACTTAAAGAGACTTAAAGTGCAGATTCATTATAAATATGCAGATTCCGAGTAAGCGAGTAAGTGCAGATTCAGACTTAAAGAGACTTAAAGGGACTCGGTCCGAGTAAGATTATAAATAGGACTCGGTCGGACTCGGTCGGACTCGGTCCGAGTAAGCGAGTAAGTGCAGATTCATTATAAATAAGACTTAAAGAGACTTAAAGCGAGTAAGTGCAGATTCGGACTCGGTCCGAGTAAGTGCAGATTCTGCAGATTCGGACTCGGTCCGAGTAAGGGACTCGGTCTGCAGATTCTGCAGATTCTGCAGATTCCGAGTAAGAGACTTAAAGGGACTCGGTCGGACTCGGTCCGAGTAAGAGACTTAAAGAGACTTAAAGGGACTCGGTC"
k = 14
FrequentWords(text, k)
